#!/bin/bash

set -euo pipefail

force=
if [[ "${1:-}" == "-f" ]]; then
    force=1
fi

dryrun=
if [[ "${1:-}" == "-d" ]]; then
    dryrun=1
fi

git remote prune origin

get_branches() {
	git branch -vv | grep -F ': gone]' | sed 's/^\*\s*//' | awk '{print $1}'
}

set +e
branches=$(get_branches)
set -e

if [[ "$dryrun" -eq 1 ]]; then
    if [[ -n "$branches" ]]; then
        for branch in $branches; do
            echo "  ${branch}"
        done
    fi
    exit
fi

if [[ -n "$branches" ]]; then
    if [[ "$force" -eq 1 ]]; then
        echo "Deleting branches: "
        for branch in $branches; do
            echo "  ${branch}"
        done
        git branch -D $branches
    else
        echo "Will delete branches: "
        for branch in $branches; do
            echo "  ${branch}"
        done
        echo

        while true; do
            read -rp "Delete? (y/n) "
            case $REPLY in
                Y|y)
                    git branch -D $branches
                    break
                    ;;
                N|n)
                    break
                    ;;
                *)
                    echo "Please enter 'y' or 'n'"
                    ;;
            esac
        done
    fi
else
	echo "Nothing to do"
fi

