#!/bin/bash

set -euo pipefail

branch=master
if [[ "${1:-}" == "-b" ]]; then
    branch=$2
    shift 2
fi

# If we're not on $branch, don't switch to $branch if there's nothing to purge
# If we are on $branch, we want to pull in updates
if [[ "$(git rev-parse --abbrev-ref HEAD)" != "$branch" ]]; then
    if [[ -z "$(git purge -d)" ]]; then
        echo "Nothing to do"
        exit
    fi

    echo "Checking out $branch..."
    git checkout "$branch"
    echo
fi

echo "Pulling from $branch..."
git pull
echo

echo "Purging branches..."
git purge "$@"
